steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'create-env']
  env:
    - 'DATABASE_URL=${_DATABASE_URL}'
    - 'DATABASE_URL_TEST=${_DATABASE_URL_TEST}'
    - 'NODE_ENV=${_NODE_ENV}'
    - 'PORT=${_PORT}'
    - 'SECRET_KEY=${_SECRET_KEY}'
    - 'TOKEN_EXPIRATION=${_TOKEN_EXPIRATION}'
    - 'TOKEN_ISSUER=${_TOKEN_ISSUER}'
    - 'TOKEN_AUDIENCE=${_TOKEN_AUDIENCE}'
    - 'MAILER_EMAIL=${_MAILER_EMAIL}'
    - 'SENDGRID_API_KEY=${_SENDGRID_API_KEY}'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'migrate']
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'codecov-coverage']
  env:
    - 'CODECOV_TOKEN=${_CODECOV_TOKEN}'
  timeout: '600s'
