export const Posted = 0 // Internal (Not from JTL this reflects Orders table in Endeavour databases)
export const Acknowledged = 1
export const Shipped = 2
export const Canceled = 3
export const Pending = 4
export const Preparation = 5
export const Pickprocess = 6
export const Locked = 7
export const PartiallyShipped = 8
export const PartiallyCanceled = 9
